<template>
  <div class="hello">
    <h2>{{ message }}</h2>
    <p>{{ description }}</p>
    <button @click="handleClick" class="btn">Click me!</button>
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  props: {
    message: String
  },
  data() {
    return {
      description: 'This is a sample Vue component generated by Fastify CLI.'
    }
  },
  methods: {
    handleClick() {
      alert('Hello from Vue component!');
    }
  }
}
</script>

<style scoped>
.hello {
  padding: 2rem;
  border: 1px solid #e1e1e1;
  border-radius: 8px;
  margin: 1rem 0;
}

.btn {
  background-color: #42b883;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  cursor: pointer;
  font-size: 1rem;
}

.btn:hover {
  background-color: #369870;
}
</style>